version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=chemicaldb
    depends_on:
      - db
    restart: always
  
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chemicaldb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  data-loader:
    build:
      context: ./csv_migration
      dockerfile: Dockerfile
    container_name: data-loader-container
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=chemicaldb
    restart: on-failure
    networks:
      - default

volumes:
  db_data:
